packages:
  - 'packages/*'
  - 'tooling/*'

catalogs:
  dev:
    '@types/node': ^22.17.2
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.33.0

    prettier: ^3.6.2
    rollup: ^4.46.2
    typescript: ^5.9.3
    vitest: ^3.2.4
    "@rollup/plugin-typescript": ^12.1.4
    "@rollup/plugin-node-resolve": ^16.0.3
    "@rollup/plugin-terser": ^0.4.4
    "@rollup/plugin-alias": ^5.1.1
    "rollup-plugin-copy": ^3.5.0
    "tsx": ^4.20.6
    "jiti": ^2.6.1
    "tsdown": ^0.15.8
    "@pixpilot/rollup-plugin-size-limit": ^0.1.3
  prod:
    "@manypkg/get-packages": ^3.1.0
    "bytes": ^3.1.2
    glob: ^11.0.3
