# .github/workflows/release.yml

name: Release Package

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  ci:
    name: Run CI Checks
    # Supported: Calling a reusable workflow in the same repo is valid per https://docs.github.com/en/actions/how-tos/sharing-automations/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASER_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          registry-url: 'https://registry.npmjs.org'

      - uses: pixpilot/github/actions/semantic-release-protected-branch@main
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          USER_ID: ${{ steps.generate_token.outputs.user-id }}
          APP_SLUG: ${{ steps.generate_token.outputs.app-slug }}
          NPM_TOKEN: ${{  secrets.NPM_TOKEN }}
