# .github/workflows/release.yml

name: Release Package

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  ci:
    name: Run CI Checks
    # Supported: Calling a reusable workflow in the same repo is valid per https://docs.github.com/en/actions/how-tos/sharing-automations/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/ci.yml

  release:
    uses: pixpilot/github/actions/semantic-release-protected-branch@main
    needs: ci
    secrets:
      RELEASER_ID: ${{ secrets.RELEASER_ID }}
      RELEASER_PRIVATE_KEY: ${{ secrets.RELEASER_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
