name: Reusable Release Steps

on:
  workflow_call:
    secrets:
      RELEASER_ID:
        required: true
      RELEASER_PRIVATE_KEY:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASER_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Configure Git user
        run: |
          git config --global user.name "${{ steps.generate_token.outputs.app-slug }}[bot]"
          git config --global user.email "${{ steps.generate_token.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com"

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
